### ISSUE TITLE
Investigate impact of Services Isolation work on extensions

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#100]
Prepare a proposal in scope of Services Isolation work that covers impact on Magento extensions.

The document should include:
- decomposition of Magento core packages with lowest impact on extensions
  - expected impact is clearly described
- expected work for extension developers to support new Magento structure
- gradual plan as we move through different stages of Magento evolution: modularity, services decomposition, distributed deployment
  - will it be necessary to distinguish extensions that support distributed deployment or any other changes in Magento framework?
- changes to Marketplace extension submission workflow

Include Ravi Menon, Lars Roettig, Navarr Barnier, Kristof Fooman to discussions on this topic.

**Comment by buskamuza** [comment]
https://github.com/magento/architecture/issues/88

**Comment by piotrekkaminski** [comment]
- investigate if tooling can be created to ease transition
