### ISSUE TITLE
Update "Magento MFTF Tests Versioning and Backward compatibility Policy" with modifying argument type  for ActionGroup

### ISSUE THREAD

**Issue by irenelagno** [magento/architecture#103]
The following documents should be updated to reflect that changing argument type for ActionGroup  is a breaking change:

* https://github.com/magento/architecture/blob/master/design-documents/testing/functional/versioning-and-backward-compatibility-policy.md
  
**Action Group entity:**

  |xPath|idAttribute|
  |---|---|
  |`/actionGroups/actionGroup`|type|

**Comment by joni-jones** [comment]
Merged
