### ISSUE TITLE
SVC Improvements

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#107]
SVC (Semantic Versioning Checker) is a tool that validates presence of breaking changes. Used for PRs as team merge code to mainline.

AC:
- move SVC to a public repo, so community could contribute (both code and suggestions)
- proposal for added coverage for:
  - GraphQL schema
  - XML changes
  - improve DB changes detection:
    - make whitelists more granular
    - more granular reports for changes in `db_schema_whitelist.json` files
  - investigate other areas that contribute to breaking changes

**Comment by paliarush** [comment]
Example of SVC failures when private constant is removed https://github.com/magento/magento2ce/pull/3875

**Comment by paliarush** [comment]
Proposal for improvements created in scope of https://github.com/magento/architecture/pull/128
