### ISSUE TITLE
Database MediaStorage in Magento 2

### ISSUE THREAD

**Issue by gwharton** [magento/architecture#111]
Magento 2 supports database storage mode, where the master storage location of media files is the database, and each frontend node stores a local "cached" copy of images on disk to use/serve as and when required.

The current solution is *HORRENDOUS*. 

At the moment, every piece of code that needs to access a media file, must be MediaStorage aware, must check if database storage mode is enable, and must copy the file from the database to the local storage if it doesn't exist and then do what it needs to do with the file.

A quick code inspection through Magento shows there are MANY MANY places where content in media storage is accessed either directly, or through Magento's framework filesystem routines, neither of which are database storage aware, without the necessary database checks and storage of local copies.

The whole media storage subsystem should to be extracted to a single subsystem. Every module wishing to write/read/query an item from media storage does it through a single set of Framework functions.

The media storage subsystem should be easily pluggin-able so that additional storage methods can be introduced. This would allow for combinations such as

- Filesystem only (as per default Magento)
- Database backend, copied to filesystem to serve (as per default Magento)
- Amazon S3 storage with media url's set direct to Amazon storage frontend
- Google Cloud Storage with media url's set direct to Google storage frontend
- Other plugin modules people may wish to contribute

Note, the Amazon and Google options are hugely powerful. They allow you to serve the stored content directly from their servers through their own https servers, taking the load off your own machines. This can be easily set in Magento with the media url settings. There would be NO need for ANY local media storage whatsoever which gives a big thumbs up for clustered environments.

I realise there are addon modules available for Amazon and Google storage, but they are hacks into the current system and require a *MASSIVE* amount of fudging (because the code to access the media storage location is distributed far and wide in M2)

Something to think about as at the moment, both 2.2 and 2.3 are riddled with bugs and nasties related to the database media storage functionality that only rear their head when operating in a clustered setup. (Thats the whole purpose of the DB media storage option IMO)

I'm working my way through the bugs in the current system, but the more I delve into the code, the more I realise, hang on, none of this should be visible to the end user modules.....Where the media is ultimately stored is none of my concern!..... I shouldnt have to be writing code to cache files from the database to local disk, just to check the size of the favicon file, for example.

**Comment by gwharton** [comment]
A quick code inspection of 2.3-develop shows the following potential issues.

- Magento\Framework\View\Design\Theme\Customization\Path.php
Theme customization files are read from local pub/media folder. If running in a clustered environment with media storage in database, then the user will need to ensure that the media customization files are present on every node in the cluster. They are NOT read from the database.

- Magento\Framework\Backup\Media.php
This makes a backup of the pub/media folder to local disk. This is probably ok. In a clustered environment with database media storage mode on, this will backup the contents of the pub/media folder on ONE of the nodes. This is ok, as the actual media content is stored in the database, and the pub/media folder is a mixture of static files (e.g theme customization files) and local copies of database content.

- Magento\Sales\Model\Order\Pdf\AbstractPdf.php
The logo file for inclusion in the sales pdf's is retrieved directly from the pub/media folder. When in database media storage mode, this may not exist on the node that is running this code. It should first download a copy from database into pub/media if in database media storage mode.

- Magento\Email\Model\AbstractTemplate.php
The logo file for inclusion in sales emails is retrieved directly from the pub/media folder. When in database media storage mode, this may not exist on the node that is running this code. It should first download a copy from database into pub/media if in database media storage mode.

- Magento\Cms\Helper\Wysiwyg\Images.php
getCurrentPath seems to operate on local pub/media folder even in database media storage mode. This affects functions like Magento\Cms\Block\Adminhtml\Wysiwyg\Images\Tree.php which will show folders only present on local pub/media, and not what is in the database. This may be empty on new cluster nodes.

- Magento\Swatches\Controller\Adminhtml\Iframe\Show.php
Appears to store uploaded swatch files directly to media folder, and not database.

- Magento\Captcha\Cron\DeleteExpiredImages.php
Deletes expired images from local storage. Are captcha images stored in db? Do captcha images need to be persistent and accessible via all nodes in a cluster?

- Magento\Captcha\Helper\Data.php
Uses local dir for captcha images. Are captcha images stored in db? Do captcha images need to be persistent and accessible via all nodes in a cluster?

- Magento\Eav\Model\Attribute\Data\File.php
Appears to upload and process files in media folder directly. What are these files, and do all nodes in the cluster require access to them. Currently they will only be uploaded to the media folder on the node processing the request. Even then, when this cluster node is destroyed and reintroduced with a fresh node, with a clean pub/media folder, the file may be lost forever.

- Magento\ProductVideo\Controller\Adminhtml\Product\Gallery\RetrieveImage.php
Attempts to get image information from video file located in pub/media folder. When in database media storage mode, this may not exist on the node that is running this code. It should first download a copy from database into pub/media if in database media storage mode.

- Magento\Analytics\Model\FileRecorder.php
Records new files to local pub/media folder. Are these files intended to be accessed from future requests from other nodes in the cluster, or externally through http? This may fail if they only exist on one of the nodes and are not placed in database media storage.

- Magento\Catalog\Block\Product\Gallery.php
This function gets the width of an image by reading from local storage. When in database media storage mode, this may not exist on the node that is running this code. It should first download a copy from database into pub/media if in database media storage mode.

- Magento\MediaStorage\Service\ImageResize.php <- BUG [#21546](https://github.com/magento/magento2/issues/21546)
Function called everytime a product is saved to generate cached images. Processes images on local pub/media folder and does not store cached copies in database. Infact, it fails to do either, as detailed in [#21546](https://github.com/magento/magento2/issues/21546)

- Magento/Catalog/Block/Adminhtml/Product/Helper/Form/Gallery/Content.php <- BUG [#21604](https://github.com/magento/magento2/issues/21604)
When displaying the Adminhtml Product Edit, Images and Videos section, the code attempts to verify the existence of the product images on the local pub/media folder. If they do not exist, then the admin page shows placeholder image instead of product image. When in database media storage mode, this may not exist on the node that is running this code. It should first download a copy from database into pub/media if in database media storage mode.

I don't know what the impact of some of the above are, but clearly there are some issues to resolve. This is purely by code analysis only and no testing has been performed (apart from the last two which have bugs raised).

**Comment by gwharton** [comment]
Is running Magento on a load balanced clustered setup supported? Seems like its not actually compatible with some fundamental implementations.

Take the image uploader for example. A temporary image is uploaded into pub/media/tmp and a copy of the temporary image is stored in the database.

When you click Save (which could be processed on a completely different physical node) the pub/media/tmp image is not there, however the database image is!

**Comment by buskamuza** [comment]
Thank you, @gwharton, for the details. We have a similar item about improving file system framework in our backlog. I'll link your feedback there, so we don't miss the details.

cc @piotrekkaminski from the Product team.

**Comment by gwharton** [comment]
No problems, i'll plug away at the headline bugs (well to be brutally honest, I'll continue until i've fixed all of the issues affecting my store), but it could really do with much more radical rework. I'll leave that there :)

**Comment by gwharton** [comment]
Closing as alot of progress has been made on this since opening the issue.
