### ISSUE TITLE
Release ece-tools outside of cloud/commerce

### ISSUE THREAD

**Issue by gamort** [magento/architecture#127]
The ece-tools package is a thing of beauty.  Command line build and deployment tools. Docker compose file creation. An elegant core patch system. Having this tool publicly available would help so many who currently have to roll their own solutions

**Comment by buskamuza** [comment]
@gamort , thanks for the feedback.
https://github.com/magento/ece-tools is public (was open somewhere around Feb this year). Should we consider this issue resolved or did you mean something else?

**Comment by buskamuza** [comment]
Closing the issue considering it resolved. Feel free to open a new issue if necessary.
