### ISSUE TITLE
May 1, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#142]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/_ScfmbQC4A0)

**Comment by buskamuza** [comment]
- Backward Compatibility policy updates - https://github.com/magento/devdocs/pull/4323 (15min)

**Comment by buskamuza** [comment]
* Raising the severity of [insecure function sniff](https://github.com/magento/magento-coding-standard/blob/develop/Magento2/Sniffs/Security/InsecureFunctionSniff.php) to 10 (error) for extensions submitted to Marketplace. (@ravmenon )

**Comment by ravmenon** [comment]
Confirmed that we will be raising the severity to 10 (error)
