### ISSUE TITLE
May 8, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#153]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/J5b-KnPy4kc)

**Comment by sivaschenko** [comment]
Adobe Stock Integration https://github.com/magento/architecture/pull/155 (15 min)

**Comment by buskamuza** [comment]
https://github.com/magento/architecture/pull/157 (15 min)

**Comment by lenaorobei** [comment]
Adding `json_encode`/`json_decode` to list of insecure functions https://github.com/magento/magento-coding-standard/pull/91 (5 min)
