### ISSUE TITLE
May 22, 2019

### ISSUE THREAD

**Issue by sivaschenko** [magento/architecture#164]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/no2jVn_mixk)

**Comment by sivaschenko** [comment]
Compiled interceptors module https://github.com/magento/magento2/pull/22826 (15 mins)

**Comment by maghamed** [comment]
Immutable DTO with immutable extension attributes by Riccardo Tempesta (15 min)

**Comment by maghamed** [comment]
Fixing performance/scalability issue on cache invalidation mechanism 
https://twitter.com/IvanChepurnyi/status/1127196189982638081
https://github.com/magento/magento2/pull/22829

**Comment by kalpmehta** [comment]
Implicitly escape HTML/JS code to prevent XSS vulnerabilities

https://twitter.com/kalpmehta/status/1129121495760789504
