### ISSUE TITLE
June 19, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#183]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [recording](https://youtu.be/MzLabezbnMI)

**Comment by lenaorobei** [comment]
- The use of `$this->helper(<helper_class>)` in `phtml` templates https://github.com/magento/magento-coding-standard/issues/108 (10 min)

**Comment by joni-jones** [comment]
JWT support out-of-box https://github.com/magento/architecture/pull/188 (10min)

**Comment by AlexMaxHorkun** [comment]
Read custom layout updates from files https://github.com/magento/architecture/pull/187/

**Comment by paliarush** [comment]
Alternative Checkout Flow https://github.com/magento/architecture/pull/192

**Comment by buskamuza** [comment]
* Using helpers in templates
  * @joni-jones , @akaplya : it should not be necessary to use helpers, and it should be possible to refactor templates to use view models instead.
  * ✅ preserver the rule in phpcs, no exceptions for templates
  * ✅ make sure that there is a static test that verifies no `phpcs:disable` added
* JWT support
  * @AlexMaxHorkun : will it be used by anything existing in vanilla Magento? @joni-jones : yes, Cardinal Commerce for 3d secure
  * ✅ no critical objections. Proceed with the proposal review offline
* Alternative Checkout flow
  * @antonkril : add definitions of Cart and Quote
  * @antonkril : why there is separate "Applicable cart rules calculator" service? Will it ever be used w/o Quote? 
     * Can be used for calculating estimates in minicart
  * @antonkril : cart rules should not be passed by the client to the Quote. @paliarush : should be under the hood, not from the client. This part should be clarified in the document
  * @antonkril : why do we need totals entity?
  * Billing address should not be part of quote
  * @antonkril : if cart is broken down to quotas by shipping addresses, how to apply discounts applicable only to entire cart?
