### ISSUE TITLE
July, 10, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#199]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/zC5ka1iX4vw)

**Comment by buskamuza** [comment]
View models to be considered public API (10min)

**Comment by sivaschenko** [comment]
https://github.com/magento/magento2/pull/18541 View models sharable by default (15min)

**Comment by AlexMaxHorkun** [comment]
Content Security Policies https://github.com/magento/architecture/pull/202 (15 min)

**Comment by AlexMaxHorkun** [comment]
Controllers for web API https://github.com/magento/architecture/pull/203 (15 min)

**Comment by buskamuza** [comment]
* View Models - public API
  * @akaplya : ok with assumption that it's API only (not SPI) - constructor can change, new methods can be added
* CSP
  * @joni-jones : should have only one of whitelist or API or both should support same features. @AlexMaxHorkun : themes don't need to implement complex policies
  * @melnikovi : reporting may add performance impact
  * @DrewML : browser extensions will trigger CSP, most likely each visitor will trigger it
  * Even vanilla Magento does not allow strict CSP mode, need a plan on how to implement CSP
