### ISSUE TITLE
July 17, 2019

### ISSUE THREAD

**Issue by danielrenaud** [magento/architecture#205]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/6O6dHac_ijU)

**Comment by danielrenaud** [comment]
Domain Whitelist for Configurable 3rd Party Redirects: https://github.com/magento/architecture/pull/204

**Comment by buskamuza** [comment]
DB changes in versioning policy - https://github.com/magento/devdocs/pull/4969 (5min)

**Comment by buskamuza** [comment]
* Translatable phrases
  * @kandy, @DrewML : make it MINOR, English is OK.
  * @paliarush : let's distinguish positive (MAJOR) and negative scenario, like errors in user input/etc (MINOR).
  * collect feedback from community on making it MINOR
  * add explanation why PATCH
* DB breaking changes - engine change
  * discuss with @akaplya 
* Domain Whitelist for Configurable 3rd Party Redirects
  * Rely on the backend domain for now. Add whitelisting in the future if there will be a real use case where frontend can be on a different domain than the backend. The functionality looks additive, so it should not require breaking changes
