### ISSUE TITLE
July 24, 2019

### ISSUE THREAD

**Issue by cspruiell** [magento/architecture#212]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

🎥 [Recording](https://youtu.be/Riq6Ng-K-Ns)

**Comment by cspruiell** [comment]
Add Scope to CMS Pages: https://github.com/magento/architecture/pull/209

**Comment by paliarush** [comment]
https://github.com/magento/architecture/pull/211 (5 min)
https://github.com/magento/architecture/pull/208 (10 min)

**Comment by davemacaulay** [comment]
Static test requiring equal PHP versions between only Magento modules and root `composer.json`, where as other modules only have to support the same versions as root but can support others.

**Comment by buskamuza** [comment]
* Scopes for CMS pages
  * Consider EAV structure
  * Resolve questions with PO
* Apollo schema federation for GraphQL
  * No concerns
* GraphQL subscriptions evaluation
  * No concerns
* Static test requiring equal PHP versions between only Magento modules and root `composer.json`
  * Fix the test to allow equal or more supported PHP versions by a Magento module
