### ISSUE TITLE
August 7, 2019

### ISSUE THREAD

**Issue by michaelyu0123** [magento/architecture#222]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:00am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/5NWYM6n3rW8)

**Comment by michaelyu0123** [comment]
HLD for JS compatibility check for AMD modules marked with @api (10min)

**Comment by lenaorobei** [comment]
The use of helpers in templates coding standard rule  https://github.com/magento/magento-coding-standard/pull/122

**Comment by buskamuza** [comment]
Translations in di.xml - https://github.com/magento/architecture/pull/223 (10min)

**Comment by jedmao** [comment]
Apollo Federation Gateway https://github.com/magento/architecture/pull/224

**Comment by lenaorobei** [comment]
**Coding standard rule:** classes and interfaces PHPDoc formatting https://github.com/magento/magento-coding-standard/issues/105 (5 min)

**Comment by buskamuza** [comment]
* Coding standards for phpdoc blocks: do not require dock block for classes
* Coding standards for view models vs helpers: yes, add such rule. View models can be marked as `@api` later.
* Translations in `di.xml` - it's a bad place for translations. Investigate if it's possible to eliminate this feature at all.
