### ISSUE TITLE
Update to PSR12

### ISSUE THREAD

**Issue by paul-gene** [magento/architecture#225]
As per https://github.com/magento/magento-coding-standard/issues/128

Would like to see the M2 coding Standards ruleset be updated to use PSR12 in place of PSR2.

**Comment by buskamuza** [comment]
No objections for moving to PSR12. Things to consider:
- impact on dev experience when switching to PSR12 (any rules that are more strict than in PSR2)

Having a proposal document highlighting changes in dev experience would be helpful.
For now, added this question to Arch meetings agenda (https://github.com/magento/architecture/issues/258)

**Comment by buskamuza** [comment]
Even with some impact, it makes sense to move on and switch to PSR12. So if somebody can implement it, it would be great.
cc @lenaorobei
