### ISSUE TITLE
August 14, 2019

### ISSUE THREAD

**Issue by zetlen** [magento/architecture#227]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/P3HmYOWzue4)

**Comment by zetlen** [comment]
RoutableInterface proposal for PWA to route all URLs: #226 (15 min.)

**Comment by buskamuza** [comment]
* @kandy : how Magento will know what's the typename? 
* @paliarush : it may be hard to define what's the product type.

**Comment by buskamuza** [comment]
* @akaplya : https://github.com/magento/architecture/pull/230
  * @kandy : SKU should not be unique, this is a business rule
  * @melnikovi : some merchants may sell products from different companies, which SKUs overlap
      * @akaplya : we need uniqueness. The use case can be solved by using other attributes.
  * Work with PO to confirm behavior
  * Add more details about how the tool (upgrade) will work
