### ISSUE TITLE
August 21, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#234]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/sBd0b0gz0to)

**Comment by buskamuza** [comment]
* MySQL 8 auto_increment https://github.com/magento/architecture/pull/233 (20min)

**Comment by melnikovi** [comment]
Update to exception handling section in technical guidelines https://github.com/magento/devdocs/pull/5209 (10 min)

**Comment by melnikovi** [comment]
Marking interfaces with @api annotation in patch releases (10 min)

**Comment by buskamuza** [comment]
* Adding `@api` annotation in patch releases
   * Cons: this will require to bump MINOR
   * ✅ We should not add `@api` in patch releases
       * Drawbacks: those APIs can't be used (extension developers and contributors will have to use it as private code). Also, we may miss marking some API if dev team doesn't create a task for it and it's not prioritized (can be solved by improving process).
