### ISSUE TITLE
September 4, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#258]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/nQ4b8TrXG5c)

**Comment by tariqjawed83** [comment]
Consumer processes improvements, https://github.com/magento/architecture/pull/232 (10 mins)

**Comment by buskamuza** [comment]
PSR12 https://github.com/magento/architecture/issues/225 (5min)

**Comment by buskamuza** [comment]
auto_increment in MySQL 8 https://github.com/magento/architecture/pull/233 (15min)

**Comment by buskamuza** [comment]
* Consumer improvements - looks good
* PSR12 - looks good
* MySQL auto_increment
   * add https://github.com/magento/architecture/pull/233#issuecomment-524468006 to the possible solutions.
   * @akaplya : fix import to not rely on auto_increment. Document different behavior of `showTableStatus()` with MySQL 8.
   * For 2.4, remove `showTableStatus()` (deprecate first) and replace with more specific methods for what we really need.
   * @melnikovi , @buskamuza : implement a workaround for 2.3.
   * (/) Solution:
      * refactor Magento core to not use table status
      * deprecate `showTableStatus()`
      * implement a workaround for `showTableStatus()` in 2.3
