### ISSUE TITLE
October 09, 2019

### ISSUE THREAD

**Issue by larsroettig** [magento/architecture#316]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/-Wpnh9S1KVE)

**Comment by ihor-sviziev** [comment]
Declarative Schema - Add OnUpdate operation for constraints - https://github.com/magento/architecture/issues/310

**Comment by buskamuza** [comment]
https://github.com/magento/architecture/pull/306 15min

**Comment by paliarush** [comment]
GraphQL schema for product reviews #298 (5 min)

**Comment by buskamuza** [comment]
* DB Information Schema - COLUMNS 
   * @akaplya : Can we make `$connectionName` optional or pass in the constructor to simplify thw interface?
* GraphQL schema for product compare
  * @buskamuza : create list (for guest) and get list (for logged in customer) make flows more complicated.
