### ISSUE TITLE
October 23, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#328]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

Time: 10:30am CST/CDT

BlueJeans Meeting - https://bluejeans.com/7385677850

🎥 [Recording](https://youtu.be/yzs9xBvGHeU)

**Comment by buskamuza** [comment]
- Asynchronous image resizing (https://github.com/magento/architecture/pull/325) - 5min

**Comment by paliarush** [comment]
- Multi-service architecture details https://github.com/magento/architecture/pull/319 (30 min)

**Comment by lenaorobei** [comment]
- Wishlist GraphQL schema https://github.com/magento/architecture/pull/326 - 10 min

**Comment by melnikovi** [comment]
Introduction of enums https://github.com/magento/architecture/pull/327 - 10 min

**Comment by melnikovi** [comment]
Adding dependencies on new packages in patch releases - 5 min

**Comment by cpartica** [comment]
API doesn't work across multiple devices  https://github.com/magento/architecture/pull/321

**Comment by buskamuza** [comment]
* Asynchronous image resizing - looks good
* Multi-service architecture details
* Wishlist GraphQL schema
  * @kandy : can we use SKU for wishlist items? @lenaorobei : no, items are configured products, so SKU is not enough. @akaplya : wishlist may have different items based on the same product, but configured differently
  * @paliarush : `createWishlist` should be aligned with create empty cart behavior.
  * Taking into account Magento Commerce has multi-wishlist, `wishlist` query should return an array
  * `id` from `Int` to `ID` is a breaking change, should be postponed till minor release. @buskamuza : describe drawbacks of postponing the change vs introducing it now, discuss with PO.
  * Additional discussion is needed
* GraphQL schema for EAV attributes metadata
* Introduction of enums
  * @buskamuza : update the document to make it more clear which solution is chosen
  * @kandy : provide performance measurements of enums vs strings
* Adding dependencies on new packages (libraries) in patch releases
  * It's a breaking change because an extension may already depend on the same lib, but of different version
     * @kandy : if we depend on `*` it might be non-breaking
  * major if depend on more strict version
* graphql cart API doesn't work across multiple devices & once logged in we need to import products from guest cart to customer
  * Additional discussion is needed
