### ISSUE TITLE
Add PHP 7.4 support 

### ISSUE THREAD

**Issue by ihor-sviziev** [magento/architecture#344]
PHP 7.4 [got released](https://www.php.net/archive/2019.php#2019-11-28-1).

Is there any plans to support it new php version?

**Comment by Eddcapone** [comment]
PHP 7.4.9 does not work correctly yet.
https://github.com/magento/magento2/issues/29865#issuecomment-686583574

**Comment by ihor-sviziev** [comment]
Php 7.4 support is available in magento 2.4.0. I'm closing this issue.

**Comment by Eddcapone** [comment]
Then please try PHP 7,4,9 and try to login in the frontend as a customer.
https://github.com/magento/magento2/issues/29865
