### ISSUE TITLE
December 12, 2018

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#47]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* [Service contracts technical guidelines](https://github.com/magento/devdocs/pull/3421) (@paliarush )
   * Alex to process feedback
* [Updates to service isolation proposal](https://github.com/magento/architecture/pull/54) (@melnikovi )
* [Checkout service - early draft](https://github.com/magento/architecture/pull/53/files) (@melnikovi )
   * Igor to look at new Inventory API
* Workarounds for blockers described in [MDE Project Structure](https://github.com/magento/architecture/blob/master/design-documents/mde-project-structure.md#blockers)
   * Move on with the current workaround

🎥 [Recording](https://magento.zoom.us/recording/share/IUTjBFl3F6gvJ6aJkCDKnSxCLefvok7ZN76dzKHXpBiwIumekTziMw)

**Comment by kirmorozov** [comment]
Hi @buskamuza Here is one more thing for meeting: 
https://github.com/magento/magento2/pull/19517
Drop support of IE10 and below.
And please let me know time.

**Comment by buskamuza** [comment]
@kirmorozov , it's 10:30am (Austin time, CST). See https://github.com/magento/architecture/wiki#architectural-discussion-meetings

**Comment by ishakhsuvarov** [comment]
* Workarounds for blockers described in [MDE Project Structure](https://github.com/magento/architecture/blob/master/design-documents/mde-project-structure.md#blockers) (5 min)
