### ISSUE TITLE
January 9, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#55]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* https://github.com/magento/magento2/pull/19517 Promise-based implementation of requirejs
  * @DrewML:  need more input from @kirmorozov with proof that the change is necessary
* [Sniffs Consolidation](https://github.com/magento/architecture/pull/51)
* URL Rewrites https://github.com/magento/architecture/pull/61  
  * @akaplya: both delayed URL rewrites generation and skipping approaches should exist in the system. Skipping approach should be used as a fallback when the generation is not done yet.
     * Collisions handling: 1) fallback to the skipped generation approach; 2) provide UI for the customer to fix the collision.
  * Action items: 1) address review feedback for the implementation (performance and load testing); 2) create a story to implement background URL rewrites generation (including performance requirements/tests).
* https://github.com/magento/devdocs/pull/3316 - the changes can be merged. Docs for older Magento versions to be reverted and processed separately.
* Unify https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html (not version it)
  * @lenaorobei: current approach is better
  * @paliarush , @buskamuza : use unified approach
  * Collect more feedback. No reason to change anything unless confirmed by more feedback
* Move Tech Guidelines to arch repo - not necessary

🎥 [Recording](https://youtu.be/uZtsbpFqVxI)

**Comment by buskamuza** [comment]
From @kirmorozov:
Hi @buskamuza Here is one more thing for meeting:
magento/magento2#19517 Promise-based implementation of requirejs, keeps the same interface for require, define,
Drop support of IE10 and below.
And please let me know time.

**Comment by lenaorobei** [comment]
Hi @buskamuza. Please add the topic about [Sniffs Consolidation](https://github.com/magento/architecture/pull/51). Thank you.

**Comment by buskamuza** [comment]
https://github.com/magento/devdocs/pull/3316 , 5min

**Comment by buskamuza** [comment]
Unified document for https://devdocs.magento.com/guides/v2.3/coding-standards/technical-guidelines.html, 10min

**Comment by cpartica** [comment]
Please add topic about [Skip url generating for products in category and add computation on request](https://github.com/magento/architecture/pull/61), 15min
