### ISSUE TITLE
January 23, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#59]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* Upgrading jQuery to 3.3.1 magento/magento2#15531
  * @buskamuza, @DrewML : move to 2.4
* Upgrade to Promise-based requirejs magento/magento2#19517
  * need updates on debugging and performance improvements from @kirmorozov
* Allow class property for referenceBlock node of layout configuration magento/magento2#18933
  * To prepare a proposal with pros and cons
     * Cons: conflicts between extensions if classes don't follow same contract
* https://github.com/magento/architecture/pull/69
* @kirmorozov: PHP 7.4 preload for Magento 2.4

Recording: TBD

**Comment by sivaschenko** [comment]
Pull requests by @kirmorozov (Kirill will participate at the meeting)
Upgrade to Promise-based requirejs https://github.com/magento/magento2/pull/19517
Upgrading jQuery to 3.3.1 https://github.com/magento/magento2/pull/15531

**Comment by AlexMaxHorkun** [comment]
Allowing alias for SOAP operations
 
https://github.com/magento/architecture/pull/69
 
15 min

**Comment by kirmorozov** [comment]
PHP 7.4 Preload origins: https://github.com/magento/community-features/issues/98
RFC - https://wiki.php.net/rfc/preload
Git Commit - php/php-src@f6d227e
