### ISSUE TITLE
Page Builder Extensibility

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#73]
Review current extensibility strategy for Page Builder. Propose a long-term and short-term improvements, if necessary.

**Comment by DrewML** [comment]
The team, after being presented with all options, decided to move ahead with the "compile for life" solution outlined in the confluence doc.

https://wiki.corp.magento.com/pages/viewpage.action?spaceKey=COREENG&title=Page+Builder+Extensibility+Problem
