### ISSUE TITLE
February 6th, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#75]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* _note one..._

Recording: no recording due to tech difficulties

**Comment by buskamuza** [comment]
[Technical guidelines: Clarify what to do when service contracts already exist in a module not suffixed with "Api"](https://github.com/magento/devdocs/pull/3524) - @buskamuza (5min)

**Comment by sivaschenko** [comment]
Proposal: Allow class attribute for referenceBlock type in layout xml - @slitvyachenko (5 min)
Proposal: https://github.com/magento/architecture/pull/85
Pull Request: https://github.com/magento/magento2/pull/18933
