### ISSUE TITLE
February 20th, 2019

### ISSUE THREAD

**Issue by buskamuza** [magento/architecture#76]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* https://github.com/magento/architecture/pull/85 - looks good, give us a couple days to check with other requested reviewers
* https://github.com/magento/architecture/pull/91 - in general, looks good. Needs some clarification of details and to be checked with couple more requested reviewers
* https://github.com/magento/architecture/pull/92 (see https://github.com/magento/architecture/issues/90 for original discussion) - looks good. Let's move on and validate a real solution (with specific rules) with internal and community developers before merging. Prepare developers to such change

 🎥 [Recording](https://youtu.be/VkXpf9Hq3KM)

**Comment by lenaorobei** [comment]
### Magento Coding Standard (15 min)
- [Version Specific Rules](https://github.com/magento/magento-coding-standard/issues/17)
**New rules:**
- [Slow array SHOULD NOT be used in loop](https://github.com/magento/magento-coding-standard/issues/20)
- [The use of literal logical operators MUST be avoided](https://github.com/magento/magento-coding-standard/issues/23)
- [Multiple isset statements SHOULD be combined into one](https://github.com/magento/magento-coding-standard/issues/27)
- [Function/method call in for loop declaration MUST be avoided](https://github.com/magento/magento-coding-standard/issues/28)
-  [Do not use setTemplate in Block classes](https://github.com/magento/magento-coding-standard/issues/31)
- [Add declare(strict_types=1) to your PHP files](https://github.com/magento/magento-coding-standard/issues/33)

**Comment by sivaschenko** [comment]
Proposal: Allow class attribute for referenceBlock type in layout xml - @slitvyachenko (5 min)
Proposal: https://github.com/magento/architecture/pull/85
Pull Request: https://github.com/magento/magento2/pull/18933

**Comment by lenaorobei** [comment]
[Using phpro/grumphp for local quality check](https://github.com/magento/magento-coding-standard/issues/35) (5 min)
@larsroettig

**Comment by vzabaznov** [comment]
Proposal: Introduce a way to restart consumers https://github.com/magento/architecture/pull/91

**Comment by larsroettig** [comment]
Proposal: Using phpro/grumphp for local quality check #90

**Comment by buskamuza** [comment]
@vzabaznov , @larsroettig , please specify how much time you need to present (including questions).

**Comment by buskamuza** [comment]
Let's also run it through developers when a branch with exact rules is ready.
@lenaorobei , would you share it with internal teams and find a few volunteers to try it out?
@larsroettig , can you discuss it with the community, and find volunteers to test it there?

**Comment by buskamuza** [comment]
I'd also suggest to add an explicit criteria of "not more than X sec to run" to make sure it doesn't annoy developers. 5s can be a good number or validate with the volunteers.

**Comment by lenaorobei** [comment]
@buskamuza sure, will do that.
