### ISSUE TITLE
February 13th, 2019

### ISSUE THREAD

**Issue by lenaorobei** [magento/architecture#87]
_Please add your topic as a comment to the issue. Use following format:_
Topic description and link to PR, if any (duration in min)

## Meeting Notes

* Vote on version specific rules
* Research on count in loop
* Need feedback on setTemplate
* Review and comment on commits verification tool

Recording:  no recording due to tech difficulties

**Comment by lenaorobei** [comment]
### Magento Coding Standard (20 min)
- [Version Specific Rules](https://github.com/magento/magento-coding-standard/issues/17)
**New rules:**
- [Slow array SHOULD NOT be used in loop](https://github.com/magento/magento-coding-standard/issues/20)
- [The use of literal logical operators MUST be avoided](https://github.com/magento/magento-coding-standard/issues/23)
- [Multiple isset statements SHOULD be combined into one](https://github.com/magento/magento-coding-standard/issues/27)
- [Function/method call in for loop declaration MUST be avoided](https://github.com/magento/magento-coding-standard/issues/28)
-  [Do not use setTemplate in Block classes](https://github.com/magento/magento-coding-standard/issues/31)
- [Add declare(strict_types=1) to your PHP files](https://github.com/magento/magento-coding-standard/issues/33)
- [Controllers Should Implement HTTP Method Marker Interface](https://github.com/magento/magento-coding-standard/issues/34)
- [Using phpro/grumphp for local quality check](https://github.com/magento/magento-coding-standard/issues/35) @larsroettig

**Comment by diazwatson** [comment]
What about adding rules and sniffs for CSS and JS?

I know that [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) tool can be also used for this but I have not seen anything related in the [Magento Extension Quality Program Coding Standard ](https://github.com/magento/marketplace-eqp)

**Comment by orlangur** [comment]
@diazwatson there are a lot of such sniffs in main repo: https://github.com/magento/magento2/tree/2.3-develop/dev/tests/static/framework/Magento/Sniffs/Less

For JS another tooling from JS-ecosystem is used currently but I do agree that it would be nice to make JS code as much consistent with PHP as possible.

**Comment by orlangur** [comment]
@diazwatson, 

> I know that [PHP_CodeSniffer](https://github.com/squizlabs/PHP_CodeSniffer) tool can be also used for this but I have not seen anything related in the [Magento Extension Quality Program Coding Standard](https://github.com/magento/marketplace-eqp)

https://github.com/magento/magento-coding-standard repo for now is more like a new incarnation of MEQP repo rather than a real Magento standard existed for years.

**Comment by diazwatson** [comment]
It would be nice to re organise all those repos (and maybe the sniffs in https://github.com/magento/magento2/tree/2.3-develop/dev/tests/static/framework/Magento/Sniffs/*) in just one place.

That would be a great topic for discussion for sure

**Comment by lenaorobei** [comment]
@diazwatson 

>It would be nice to re organise all those repos (and maybe the sniffs in https://github.com/magento/magento2/tree/2.3-develop/dev/tests/static/framework/Magento/Sniffs/*) in just one place.

That's exactly what [magento/magento-coding-standard](https://github.com/magento/magento-coding-standard) is introduced for. Here is the related task - https://github.com/magento/magento-coding-standard/issues/4

**Comment by orlangur** [comment]
@diazwatson,

> It would be nice to re organise all those repos (and maybe the sniffs in https://github.com/magento/magento2/tree/2.3-develop/dev/tests/static/framework/Magento/Sniffs/*) in just one place.

Yep, moving existing and working stuff from static tests somewhere to https://github.com/magento/magento2/tree/2.3-develop/lib/internal/Magento/Framework instead of making one more repo (reminds me https://xkcd.com/927/) and then improving it iteration-by-iteration with MEQP and other useful sniffs would be really great. Approach described in issue mentioned by Lena is kinda opposite.

**Comment by diazwatson** [comment]
Great!!!

**Comment by lenaorobei** [comment]
@diazwatson Magento Coding Standard will include rules for Magento 2.x only.
MEQP1 will remain the part of Marketplace until Magento 1.x we stop accepting Magento 1.x extensions.
