### ISSUE TITLE
Service Isolation -> Minimising package renaming impact

### ISSUE THREAD

**Issue by fooman** [magento/architecture#88]
As per [this](https://github.com/magento/architecture/blob/master/design-documents/service-isolation.md#split-modules) existing modules will be split into multiple packages.

This has a follow-on impact on existing extensions (ie nearly 100% of extension will require not only a new release but also a separately maintained branch). One idea to minimise the impact would be to keep the package name for CatalogAPI for existing extensions that only use the existing service contracts (ie current best practice extension get less impacted)

As an example an extension today has the following `composer.json`
```
    "require": {
        "magento/module-catalog": "^103.0.0",
```
and only uses the API interfaces. After splitting the modules ideally this should only be 
```
    "require": {
        "magento/module-catalog": "^103.0.0 | ^104.0.0",
```

This would allow the extension to be useful across both versions instead of requiring two separate versions to support both branches:

```
    "require": {
        "magento/module-catalog": "^103.0.0",
```
and
```
    "require": {
        "magento/module-catalog-api": "^100.0.0",
```

Further to allow transitioning into the end state of service isolation it would be great if this could be phased in. Once we know the split and what package names the new modules will have we can add them to the existing Catalog module.

So the existing package `magento/module-catalog` adds the following extra packages:
```
    "provide": {
        "magento/module-catalog-implementation": "self.version",
        "magento/module-catalog-admin": "self.version",
        "magento/module-catalog-storefront": "self.version",
    }
```
while the code is not yet moved out. That way it will be possible to release an extension that prepares for the split and is able to work across major release branches.

**Comment by buskamuza** [comment]
Thanks, @fooman . That's also what we're thinking about to reduce the impact for extensions.
Will be reflecting this in a proposal as we work on it.
cc @joni-jones

**Comment by joni-jones** [comment]
> So the existing package `magento/module-catalog` adds the following extra packages:

The new packages should depend on `module-catalog`, not vice versa. We want to split the business domain from the presentation layer, dependencies to other modules, etc. But the backward compatibility and extensions it's another point to discuss.

**Comment by fooman** [comment]
@joni-jones The idea is to introduce the package split gradually. The above comment is pre actual code split.

So something like this. In the 2.3 branch we have
magento/module-catalog

In 2.4 we might have 
magento/module-catalog
- provides magento/module-catalog-implementation
- provides magento/module-catalog-admin
- provides magento/module-catalog-storefront

Bonus points here for deprecation notices .

the end after the split (2.5 or possibly even later as this is a big undertaking for not only Magento but also requiring substantial work on the extension side):
magento/module-catalog
magento/module-catalog-implementation
magento/module-catalog-admin
magento/module-catalog-storefront

This is currently the best idea I could come up with to not have these massive changes drop all at once. Which again would mean 100% of extensions will require changes. And worse still require maintaining separate branches to work with Magento pre and post service isolation.
